src/java/com/uptime/servicedelivery/bean/CreateAirbaseBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.uptime.servicedelivery.bean;

import com.uptime.client.http.client.ServiceRegistrarClient;
import com.uptime.servicedelivery.http.client.ConfigClient;
import com.uptime.servicedelivery.http.client.MonitoringClient;
import com.uptime.servicedelivery.utils.vo.ApprovedBaseStationsVO;
import com.uptime.servicedelivery.utils.vo.SiteCustomerVO;
import java.io.ByteArrayInputStream;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import org.primefaces.PrimeFaces;
import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;

/**
 *
 * @author gsingh
 */
public class CreateAirbaseBean implements Serializable {
    private ApprovedBaseStationsVO approvedBaseStationsVO;
    private final List<String> customerList;
    private final List<SiteCustomerVO> siteList;

    /**
     * Constructor
     */
    public CreateAirbaseBean() {
        customerList = new ArrayList();
        siteList = new ArrayList();
        
        try {
            customerList.addAll(((AccountManageBean) FacesContext.getCurrentInstance().getExternalContext().getSessionMap().get("accountManageBean")).getCustomerAccounts());
        } catch (Exception e) {
            Logger.getLogger(CreateAirbaseBean.class.getName()).log(Level.SEVERE, e.getMessage(), e);
            customerList.clear();
        }
    }

    /**
     * Post Constructor
     */
    @PostConstruct
    public void init() {
        resetPage();
    }

    /**
     * Resets the page
     */
    public void resetPage() {
        approvedBaseStationsVO = new ApprovedBaseStationsVO();
        siteList.clear();
    }

    /**
     * Called when the Customer Account is changed
     */
    public void onCustomerChange() {
        String customerAccount;
        
        customerAccount = approvedBaseStationsVO.getCustomerAccount();
        approvedBaseStationsVO = new ApprovedBaseStationsVO();
        siteList.clear();
        if (customerAccount != null && !customerAccount.isEmpty()) {
            approvedBaseStationsVO.setCustomerAccount(customerAccount);
            siteList.addAll(ConfigClient.getInstance().getSiteCustomerByCustomer(ServiceRegistrarClient.getInstance().getServiceHostURL("Config"), customerAccount).stream().filter(vo -> vo.getSiteName() != null && !vo.getSiteName().isEmpty()).sorted(Comparator.comparing(SiteCustomerVO::getSiteName)).collect(Collectors.toList()));
        }
    }

    /**
     * Adds a new ApprovedBaseStations Object to Cassandra, if it doesn't already exist
     */
    public void createAirbase() {
        if (!MonitoringClient.getInstance().getApprovedBaseStationsByPK(ServiceRegistrarClient.getInstance().getServiceHostURL("Monitoring"), approvedBaseStationsVO.getCustomerAccount(), approvedBaseStationsVO.getSiteId(), approvedBaseStationsVO.getMacAddress()).isEmpty()) {
            FacesContext.getCurrentInstance().addMessage("growlMessages", new FacesMessage("Provided details already exists. Try another?"));
            return;
        }
        
        approvedBaseStationsVO.setPasscode(UUID.randomUUID());
        if (MonitoringClient.getInstance().createApprovedBaseStations(ServiceRegistrarClient.getInstance().getServiceHostURL("Monitoring"), approvedBaseStationsVO)) {
            ((NavigationBean) FacesContext.getCurrentInstance().getExternalContext().getSessionMap().get("navigationBean")).updateDialog("download-new-airbase");
            PrimeFaces.current().executeScript("PF('defaultDlg').show()");
        } else {
            FacesContext.getCurrentInstance().addMessage("growlMessages", new FacesMessage("Something went wrong. Contact IT Team."));
        }
    }

    /**
     * Download the current info of the recently created ApprovedBaseStations Object
     * @param approvedBaseStationsVO, ApprovedBaseStationsVO Object
     * @return StreamedContent Object
     */
    public StreamedContent download(ApprovedBaseStationsVO approvedBaseStationsVO) {
        StringBuilder content;
        
        try {
            content = new StringBuilder();
            content
                    .append("POLLING_FILES_DIRECTORY_PATH=\n")
                    .append("MAXIMUM_NUMBER_OF_WORKER_THREADS=\n")
                    .append("BASE_STATION_WEB_SERVICE_URI=\n")
                    .append("POLLING_INTERVAL=5\n")
                    .append("CUSTOMER_ACCOUNT=").append(approvedBaseStationsVO.getCustomerAccount()).append("\n")
                    .append("SITE_ID=").append(approvedBaseStationsVO.getSiteId()).append("\n")
                    .append("SITE_NAME=").append(siteList.stream().filter(vo -> vo.getSiteId().equals(approvedBaseStationsVO.getSiteId())).map(SiteCustomerVO::getSiteName).findFirst().get()).append("\n")
                    .append("HARDWARE_TOKEN=\n")
                    .append("PASSCODE=").append(approvedBaseStationsVO.getPasscode());
            
            return DefaultStreamedContent.builder()
                    .name("airbaseDetails_" + approvedBaseStationsVO.getMacAddress().replaceAll(":", "_") + ".properties")
                    .contentType("application/text")
                    .stream(() -> new ByteArrayInputStream(content.toString().getBytes()))
                    .build();
            
        } catch (Exception e) {
            Logger.getLogger(CreateAirbaseBean.class.getName()).log(Level.SEVERE, e.getMessage(), e);
        }
        
        return null;
    }
    

    public ApprovedBaseStationsVO getApprovedBaseStationsVO() {
        return approvedBaseStationsVO;
    }

    public List<String> getCustomerList() {
        return customerList;
    }

    public List<SiteCustomerVO> getSiteList() {
        return siteList;
    }
}

src/java/com/uptime/servicedelivery/utils/vo/EchoDiagnosticsVO.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.uptime.servicedelivery.utils.vo;

import java.io.Serializable;
import java.time.Instant;
import java.time.ZonedDateTime;
import java.util.Objects;
import java.util.UUID;

/**
 *
 * @author kpati
 */
public class EchoDiagnosticsVO implements Serializable {
    private String customerAccount;
    private UUID siteId;
    private String siteName;
    private String baseStationHostName;
    private String deviceId;
    private String echoFw;
    private String baseStationMac;
    private short echoDatasets;
    private short echoBacklog;
    private short echoReboot;
    private short echoPowerfault;
    private short echoRestart;
    private byte echoRadioFail;
    private byte echoTerr;
    private byte echoPowLevel;
    private Instant lastUpdate;
    private ZonedDateTime lastUpdateWithSpecfZone;
    private int index;
    
    public EchoDiagnosticsVO(){
    }

    public EchoDiagnosticsVO(String customerAccount, UUID siteId, String siteName, String baseStationHostName, String deviceId, String echoFw, String baseStationMac, short echoDatasets, short echoBacklog, short echoReboot, short echoPowerfault, short echoRestart, byte echoRadioFail, byte echoTerr, byte echoPowLevel, Instant lastUpdate, ZonedDateTime lastUpdateWithSpecfZone, int index) {
        this.customerAccount = customerAccount;
        this.siteId = siteId;
        this.siteName = siteName;
        this.baseStationHostName = baseStationHostName;
        this.deviceId = deviceId;
        this.echoFw = echoFw;
        this.baseStationMac = baseStationMac;
        this.echoDatasets = echoDatasets;
        this.echoBacklog = echoBacklog;
        this.echoReboot = echoReboot;
        this.echoPowerfault = echoPowerfault;
        this.echoRestart = echoRestart;
        this.echoRadioFail = echoRadioFail;
        this.echoTerr = echoTerr;
        this.echoPowLevel = echoPowLevel;
        this.lastUpdate = lastUpdate;
        this.lastUpdateWithSpecfZone = lastUpdateWithSpecfZone;
        this.index = index;
    }
    
    public EchoDiagnosticsVO(EchoDiagnosticsVO echoDiagnosticsVO){
        customerAccount = echoDiagnosticsVO.getCustomerAccount();
        siteId = echoDiagnosticsVO.getSiteId();
        siteName = echoDiagnosticsVO.getSiteName();
        baseStationHostName = echoDiagnosticsVO.getBaseStationHostName();
        deviceId = echoDiagnosticsVO.getDeviceId();
        echoFw = echoDiagnosticsVO.getEchoFw();
        baseStationMac = echoDiagnosticsVO.getBaseStationMac();
        echoDatasets = echoDiagnosticsVO.getEchoDatasets();
        echoBacklog = echoDiagnosticsVO.getEchoBacklog();
        echoReboot = echoDiagnosticsVO.getEchoReboot();
        echoPowerfault = echoDiagnosticsVO.getEchoPowerfault();
        echoRestart = echoDiagnosticsVO.getEchoRestart();
        echoRadioFail = echoDiagnosticsVO.getEchoRadioFail();
        echoTerr = echoDiagnosticsVO.getEchoTerr();
        echoPowLevel = echoDiagnosticsVO.getEchoPowLevel();
        lastUpdate = echoDiagnosticsVO.getLastUpdate();
        lastUpdateWithSpecfZone = echoDiagnosticsVO.getLastUpdateWithSpecfZone();
        index = echoDiagnosticsVO.getIndex();
    }

    public String getCustomerAccount() {
        return customerAccount;
    }

    public void setCustomerAccount(String customerAccount) {
        this.customerAccount = customerAccount;
    }

    public UUID getSiteId() {
        return siteId;
    }

    public void setSiteId(UUID siteId) {
        this.siteId = siteId;
    }

    public String getSiteName() {
        return siteName;
    }

    public void setSiteName(String siteName) {
        this.siteName = siteName;
    }

    public String getBaseStationHostName() {
        return baseStationHostName;
    }

    public void setBaseStationHostName(String baseStationHostName) {
        this.baseStationHostName = baseStationHostName;
    }

    public String getDeviceId() {
        return deviceId;
    }

    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }

    public String getEchoFw() {
        return echoFw;
    }

    public void setEchoFw(String echoFw) {
        this.echoFw = echoFw;
    }

    public String getBaseStationMac() {
        return baseStationMac;
    }

    public void setBaseStationMac(String baseStationMac) {
        this.baseStationMac = baseStationMac;
    }

    public short getEchoDatasets() {
        return echoDatasets;
    }

    public void setEchoDatasets(short echoDatasets) {
        this.echoDatasets = echoDatasets;
    }

    public short getEchoBacklog() {
        return echoBacklog;
    }

    public void setEchoBacklog(short echoBacklog) {
        this.echoBacklog = echoBacklog;
    }

    public short getEchoReboot() {
        return echoReboot;
    }

    public void setEchoReboot(short echoReboot) {
        this.echoReboot = echoReboot;
    }

    public short getEchoPowerfault() {
        return echoPowerfault;
    }

    public void setEchoPowerfault(short echoPowerfault) {
        this.echoPowerfault = echoPowerfault;
    }

    public short getEchoRestart() {
        return echoRestart;
    }

    public void setEchoRestart(short echoRestart) {
        this.echoRestart = echoRestart;
    }

    public byte getEchoRadioFail() {
        return echoRadioFail;
    }

    public void setEchoRadioFail(byte echoRadioFail) {
        this.echoRadioFail = echoRadioFail;
    }

    public byte getEchoTerr() {
        return echoTerr;
    }

    public void setEchoTerr(byte echoTerr) {
        this.echoTerr = echoTerr;
    }

    public byte getEchoPowLevel() {
        return echoPowLevel;
    }

    public void setEchoPowLevel(byte echoPowLevel) {
        this.echoPowLevel = echoPowLevel;
    }

    public Instant getLastUpdate() {
        return lastUpdate;
    }

    public void setLastUpdate(Instant lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    public ZonedDateTime getLastUpdateWithSpecfZone() {
        return lastUpdateWithSpecfZone;
    }

    public void setLastUpdateWithSpecfZone(ZonedDateTime lastUpdateWithSpecfZone) {
        this.lastUpdateWithSpecfZone = lastUpdateWithSpecfZone;
    }

    public int getIndex() {
        return index;
    }

    public void setIndex(int index) {
        this.index = index;
    }

    public String getFormatedLastUpdate() {
        if (lastUpdateWithSpecfZone != null) {
            String timeStamp [] = lastUpdateWithSpecfZone.toString().split("T");
            String minSec[]= timeStamp[1].split("-");
            return timeStamp[0]+" "+minSec[0];
        }
        return "";
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 23 * hash + Objects.hashCode(this.customerAccount);
        hash = 23 * hash + Objects.hashCode(this.siteId);
        hash = 23 * hash + Objects.hashCode(this.siteName);
        hash = 23 * hash + Objects.hashCode(this.baseStationHostName);
        hash = 23 * hash + Objects.hashCode(this.deviceId);
        hash = 23 * hash + Objects.hashCode(this.echoFw);
        hash = 23 * hash + Objects.hashCode(this.baseStationMac);
        hash = 23 * hash + this.echoDatasets;
        hash = 23 * hash + this.echoBacklog;
        hash = 23 * hash + this.echoReboot;
        hash = 23 * hash + this.echoPowerfault;
        hash = 23 * hash + this.echoRestart;
        hash = 23 * hash + this.echoRadioFail;
        hash = 23 * hash + this.echoTerr;
        hash = 23 * hash + this.echoPowLevel;
        hash = 23 * hash + Objects.hashCode(this.lastUpdate);
        hash = 23 * hash + Objects.hashCode(this.lastUpdateWithSpecfZone);
        hash = 23 * hash + this.index;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final EchoDiagnosticsVO other = (EchoDiagnosticsVO) obj;
        if (this.echoDatasets != other.echoDatasets) {
            return false;
        }
        if (this.echoBacklog != other.echoBacklog) {
            return false;
        }
        if (this.echoReboot != other.echoReboot) {
            return false;
        }
        if (this.echoPowerfault != other.echoPowerfault) {
            return false;
        }
        if (this.echoRestart != other.echoRestart) {
            return false;
        }
        if (this.echoRadioFail != other.echoRadioFail) {
            return false;
        }
        if (this.echoTerr != other.echoTerr) {
            return false;
        }
        if (this.echoPowLevel != other.echoPowLevel) {
            return false;
        }
        if (this.index != other.index) {
            return false;
        }
        if (!Objects.equals(this.customerAccount, other.customerAccount)) {
            return false;
        }
        if (!Objects.equals(this.siteName, other.siteName)) {
            return false;
        }
        if (!Objects.equals(this.baseStationHostName, other.baseStationHostName)) {
            return false;
        }
        if (!Objects.equals(this.deviceId, other.deviceId)) {
            return false;
        }
        if (!Objects.equals(this.echoFw, other.echoFw)) {
            return false;
        }
        if (!Objects.equals(this.baseStationMac, other.baseStationMac)) {
            return false;
        }
        if (!Objects.equals(this.siteId, other.siteId)) {
            return false;
        }
        if (!Objects.equals(this.lastUpdate, other.lastUpdate)) {
            return false;
        }
        if (!Objects.equals(this.lastUpdateWithSpecfZone, other.lastUpdateWithSpecfZone)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {

web/user/card/create-airbase.xhtml
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml" 
    xmlns:h="http://java.sun.com/jsf/html" 
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:ui="http://java.sun.com/jsf/facelets" 
    xmlns:p="http://primefaces.org/ui" 
    xmlns:po="http://primefaces.org/roma"
    xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">

    <div class="card layout-create-airbase">
        <h:form id="CreateAirbaseFormId">
            <p:panelGrid styleClass="panelgrid-layout-one">
                <p:row>
                    <p:column styleClass="right-padding width-157">
                        <p:outputLabel value="Customer" for="CreateAirbaseCustId"/>  
                    </p:column> 
                    <p:column>
                        <p:selectOneMenu styleClass="min-width-one" id="CreateAirbaseCustId" value="#{createAirbaseBean.approvedBaseStationsVO.customerAccount}">
                            <f:selectItem itemLabel="Select One" noSelectionOption="true"  itemDisabled="true" />
                            <f:selectItems value="#{createAirbaseBean.customerList}"/>
                            <p:ajax listener="#{createAirbaseBean.onCustomerChange()}" update="CreateAirbaseFormId"/>
                        </p:selectOneMenu>
                    </p:column>
                </p:row>
                <p:row>
                    <p:column styleClass="right-padding width-157">
                        <p:outputLabel value="Site" for="CreateAirbaseSiteId"/>  
                    </p:column> 
                    <p:column>
                        <p:selectOneMenu styleClass="min-width-one" id="CreateAirbaseSiteId" value="#{createAirbaseBean.approvedBaseStationsVO.siteId}" converter="uuidConverter">
                            <f:selectItem itemLabel="Select One" noSelectionOption="true"  itemDisabled="true" />
                            <f:selectItems value="#{createAirbaseBean.siteList}" var="site" itemLabel="#{site.siteName}" itemValue="#{site.siteId}"/>
                            <p:ajax update="@this CreateAirbaseFormId:CreateAirbaseSaveId"/>
                        </p:selectOneMenu>
                    </p:column>
                </p:row>
                <p:row>
                    <p:column styleClass="right-padding">
                        <p:outputLabel value="MAC Address" for="CreateAirbaseMacId"/>
                    </p:column> 
                    <p:column>
                        <p:inputText id="CreateAirbaseMacId" value="#{createAirbaseBean.approvedBaseStationsVO.macAddress}" required="true"
                                     validatorMessage="Invalid MAC Address!" maxlength="255" styleClass="min-width-one">
                            <p:ajax update="@this CreateAirbaseFormId:CreateAirbaseSaveId"/>
                            <f:validateRegex pattern="^([a-fA-F0-9]{2}[:\\.-]?){5}[a-fA-F0-9]{2}$" />
                        </p:inputText>   
                        <p:message for="CreateAirbaseMacId"/>
                    </p:column>
                </p:row>
            </p:panelGrid>
            
            <div class="center-btn-div">
                <p:commandButton id="CreateAirbaseSaveId" value="Create" styleClass="left-btn" action="#{createAirbaseBean.createAirbase()}" update="CreateAirbaseFormId" disabled="#{createAirbaseBean.approvedBaseStationsVO.customerAccount eq null or createAirbaseBean.approvedBaseStationsVO.customerAccount.length() eq 0 or createAirbaseBean.approvedBaseStationsVO.siteId eq null or createAirbaseBean.approvedBaseStationsVO.macAddress eq null or createAirbaseBean.approvedBaseStationsVO.macAddress.length() eq 0}" />
                <p:commandButton type="button" value="Cancel" onclick="PF('defaultDlg').hide()"/>
            </div>
            
            <p:blockUI block="CreateAirbaseFormId" trigger="CreateAirbaseSaveId"/> 
        </h:form>
    </div>
</ui:composition>

web/user/card/download-new-airbase.xhtml
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml" 
    xmlns:h="http://java.sun.com/jsf/html" 
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:ui="http://java.sun.com/jsf/facelets" 
    xmlns:p="http://primefaces.org/ui" 
    xmlns:po="http://primefaces.org/roma"
    xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">

    <div class="card layout-download-new-airbase">
        <h:form id="downloadNewAirbaseFormId" >
            <p:outputLabel value="Download the new airbase properties?"/>
            <div class="center-btn-div">
                <p:commandButton value="Yes" type="submit" ajax="false" styleClass="left-btn" onclick="PF('defaultDlg').hide();">
                    <p:fileDownload value="#{createAirbaseBean.download(createAirbaseBean.approvedBaseStationsVO)}"/>
                </p:commandButton>
                <p:commandButton value="No" type="button" onclick="PF('defaultDlg').hide();" />
            </div>
        </h:form> 
    </div>
</ui:composition>

web/user/card/echobase-details.xhtml
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml" 
    xmlns:h="http://java.sun.com/jsf/html" 
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:ui="http://java.sun.com/jsf/facelets" 
    xmlns:p="http://primefaces.org/ui" 
    xmlns:po="http://primefaces.org/roma">

    <div class="card layout-alarm-details">
        <p:panel header="Current Settings" styleClass="panel-layout-one">
            <p:panelGrid styleClass="panelgrid-layout-one">
                <p:row>
                    <p:column styleClass="right-padding">
                        <p:outputLabel value="Customer Acc:" for="custAccId"/>
                    </p:column>
                    <p:column>
                        <p:outputLabel id="custAccId" value="#{echobasesBean.selectedEchoDiagnosticsVO.customerAccount}"/>
                    </p:column>
                </p:row>
                <p:row>
                    <p:column styleClass="right-padding">
                        <p:outputLabel value="Site Name:" for="siteNameId"/>
                    </p:column>
                    <p:column>
                        <p:outputLabel id="siteNameId" value="#{echobasesBean.selectedEchoDiagnosticsVO.siteName}"/>
                    </p:column>
                </p:row>
                <p:row>
                    <p:column styleClass="right-padding">
                        <p:outputLabel value="Base Station Name:" for="basestationHostNameId"/>
                    </p:column>
                    <p:column>
                        <p:outputLabel id="basestationHostNameId" value="#{echobasesBean.selectedEchoDiagnosticsVO.baseStationHostName}"/>
                    </p:column>
                </p:row>
                <p:row>
                    <p:column styleClass="right-padding">
                        <p:outputLabel value="DeviceId:" for="deviceId"/>
                    </p:column>
                    <p:column>
                        <p:outputLabel id="deviceId" value="#{echobasesBean.selectedEchoDiagnosticsVO.deviceId}"/>
                    </p:column>
                </p:row>
                <p:row>
                    <p:column styleClass="right-padding">
                        <p:outputLabel value="Echo Fw:" for="echoFwId"/>
                    </p:column>
                    <p:column>
                        <p:outputLabel id="echoFwId" value="#{echobasesBean.selectedEchoDiagnosticsVO.echoFw}"/>
                    </p:column>
                </p:row>
                <p:row>
                    <p:column styleClass="right-padding">
                        <p:outputLabel value="Echo Datasets:" for="echoDatasetsId"/>
                    </p:column>
                    <p:column>
                        <p:outputLabel id="echoDatasetsId" value="#{echobasesBean.selectedEchoDiagnosticsVO.echoDatasets}"/>
                    </p:column>
                </p:row>
                <p:row>
                    <p:column styleClass="right-padding">
                        <p:outputLabel value="Echo PowLevel:" for="echoPowLevelId"/>
                    </p:column>
                    <p:column>
                        <p:outputLabel id="echoPowLevelId" value="#{echobasesBean.selectedEchoDiagnosticsVO.echoPowLevel}" />
                    </p:column>
                </p:row>
                <p:row>
                    <p:column styleClass="right-padding">
                        <p:outputLabel value="Echo Powerfault:" for="echoPowerfaultId"/>
                    </p:column>
                    <p:column>
                        <p:outputLabel id="echoPowerfaultId" value="#{echobasesBean.selectedEchoDiagnosticsVO.echoPowerfault}" />
                    </p:column>
                </p:row>
                <p:row>
                    <p:column styleClass="right-padding">
                        <p:outputLabel value="Echo RadioFail:" for="echoRadioFailId"/>
                    </p:column>
                    <p:column>
                        <p:outputLabel id="echoRadioFailId" value="#{echobasesBean.selectedEchoDiagnosticsVO.echoRadioFail}" />
                    </p:column>
                </p:row>                                    
                <p:row>
                    <p:column styleClass="right-padding">
                        <p:outputLabel value="Echo Reboot:" for="echoRebootId"/>
                    </p:column>
                    <p:column>
                        <p:outputLabel id="echoRebootId" value="#{echobasesBean.selectedEchoDiagnosticsVO.echoReboot}" />
                    </p:column>
                </p:row>
                <p:row>
                    <p:column styleClass="right-padding">
                        <p:outputLabel value="Echo Restart:" for="echoRestartId"/>
                    </p:column>
                    <p:column>
                        <p:outputLabel id="echoRestartId" value="#{echobasesBean.selectedEchoDiagnosticsVO.echoRestart}" />
                    </p:column>
                </p:row>
                <p:row>
                    <p:column styleClass="right-padding">
                        <p:outputLabel value="Echo Terr:" for="echoTerrId"/>
                    </p:column>
                    <p:column>
                        <p:outputLabel id="echoTerrId" value="#{echobasesBean.selectedEchoDiagnosticsVO.echoTerr}" />
                    </p:column>
                </p:row>
                <p:row>
                    <p:column styleClass="right-padding">
                        <p:outputLabel value="Echo Backlog:" for="echoTerrId"/>
                    </p:column>
                    <p:column>
                        <p:outputLabel id="echoBacklogId" value="#{echobasesBean.selectedEchoDiagnosticsVO.echoBacklog}" />
                    </p:column>
                </p:row>
                <p:row>
                    <p:column styleClass="right-padding">
                        <p:outputLabel value="Last Update:" for="lastUpdateId"/>
                    </p:column>
                    <p:column>
                        <p:outputLabel id="lastUpdateId" value="#{echobasesBean.selectedEchoDiagnosticsVO.formatedLastUpdate}" />
                    </p:column>
                </p:row>
            </p:panelGrid>
        </p:panel>
    </div>
</ui:composition>

web/user/card/empty.xhtml
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml" 
    xmlns:h="http://java.sun.com/jsf/html" 
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:ui="http://java.sun.com/jsf/facelets" 
    xmlns:p="http://primefaces.org/ui" 
    xmlns:po="http://primefaces.org/roma">

    <div class="card"/>
</ui:composition>

web/user/card/logout.xhtml
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml" 
    xmlns:h="http://java.sun.com/jsf/html" 
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:ui="http://java.sun.com/jsf/facelets" 
    xmlns:p="http://primefaces.org/ui" 
    xmlns:po="http://primefaces.org/roma">

    <div class="card layout-logout">
        <h:form id="topbarLogoutFormId">
            <p:panelGrid styleClass="panelgrid-layout-one">
                <p:row>
                    <p:column styleClass="right-padding">
                        <p:outputLabel value="Are you sure you want to log out?" styleClass="block-label"/>
                    </p:column>
                </p:row>
            </p:panelGrid>

            <div class="center-btn-div">
                <p:commandButton styleClass="left-btn" id="topbarLogoutYesBtnId" value="Yes" action="#{logoutBean.doLogout()}" oncomplete="PF('defaultDlg').hide()" />
                <p:commandButton type="button" value="No" onclick="PF('defaultDlg').hide()"/>
            </div>
        </h:form>
    </div>
</ui:composition>